console.log("Current:");
console.log("  ● ● ●");
console.log("  ◉ ◉ ◉   Analyzing...");
console.log("  ○ ○ ○");
console.log("\nOption 1:");
console.log("  • • •");
console.log("  ◦ ◦ ◦   Analyzing...");
console.log("  · · ·");
console.log("\nOption 2:");
console.log("  ■ ■ ■");
console.log("  □ □ □   Analyzing...");
console.log("  ▪ ▪ ▪");
console.log("\nOption 3 (Braille dots-like):");
console.log("  ⠂ ⠂ ⠂");
console.log("  ⠄ ⠄ ⠄   Analyzing...");
console.log("  . . .");
console.log("\nOption 4:");
console.log("  ✦ ✦ ✦");
console.log("  ✧ ✧ ✧   Analyzing...");
console.log("  · · ·");
